server:
  port: 8080


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo


#showSql
logging:
  level:
    com:
      example:
        demo:
         dao: debug

# dubbo config

dubbo:
  application:
    name: user-service-provide
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20883
  monitor:
    protocol: registry


